spring:
  application:
    name: spring-boot-vault-integration-demo
  cloud:
    vault:
      authentication: TOKEN
      host: localhost
      port: 8200
      #      token: 0000-0000-0000-0000
      token: hvs.j0T41Gr0vMMub9dXnGcHkIzL
      scheme: http
      kv:
        backend: kv
        default-context: credentials
  #        application-name: auth
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/springboobs'
    username: ${user-db}
    password: ${pass-db}
  config:
    import: optional:vault://

external-api:
  uri: https://external-api-demo.com/v1/
